### ISSUE TITLE
Remove data context and replace with a simple concept of template scope

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#113]
There are multiple ideas here. But I think they are something like:
- no implicit passing of thing between templates
- have control of what a "template scope" is and in general have a default which is what you would expect from function calls
- have tighter control over reactivity of values in the template scope

I would suggest we deprecate data context and make it so that arguments passed to template becomes simply attributes of the template instance. Or, alternatively, they are passed to the constructor, which by default extends the current template instances with them.

The implementation order would be something like this: we make templates be template classes, and then we provide ways to override what is a data context (nothing, to remove it), how inclusion arguments are copied to a template instance, and how the lookup of symbols inside a template is done. See #98.

How should we name it? scope? context? args? props?

**Comment by tcastelli** [comment]
IMO, If we want it to make it backwards compatible, I would go for a global option in Blaze that decides on what behaviour must be used (so we can disable the implicit passing of context globally by just setting Blaze.legacyContextBehaviour = false or something like that),
Also I would I would allow to define the context it by explicitly declaring so the constructor sets it on inizialization. By explicitly declaring it, I think we can assume that you now what it does in terms of reactivity and you should be fine with that(otherwise just don't use it and avoid those problems).

As for the name i would go for `context=` but just because I am used to that name regarding Blaze, not something logical, since scope can be fine too

**Comment by mitar** [comment]
Thank you for the suggestion and comments today! I really appreciate it. Let me give you a bit broader picture here. So my current proposal for dealing with this question of backwards compatibility is that we do not have some global options and things like that, because this makes it hard to combine multiple existing packages and templates from various sources together.

And we do not even have to do it like that. Because the idea is that we convert Blaze templates to classes. And then each class will have methods. And those methods will tell how you want your data context to behave, or if you want a data context at all.

So idea is to support something like:

```
<template is="Component" name="foo">
</template>
```

Which would be the same as:

```
<component name="foo">
</component>
```

And then you can have your base class, and Blaze will provide two (`Template`, for traditional/legacy templates, and `Component` for this new style without data context). But there will be no magic to it, just a simple class which will have different defaults.

So old apps will not see anything special. Other developers will be able to use their custom base class. And the new suggested way to do it would be a new base class without data context.

**Comment by tcastelli** [comment]
Again sorry, I didnt catch the "double template" access, since I thought the template class was the one redefined. Now I understand the point,  abd if I get it right,  the key here is defining or not the "is=" so we can use the old or the new kind of behaviour.(Kind of having a variable for every template byt more useful because we can reuse classes)

Again I see no problems then,  since the transition should be smooth then :)

**Comment by mitar** [comment]
Check out #116, there is a branch which has a rewrite to template classes done. Feel free to try it with your existing code and report back there if it is breaking anything.

**Comment by tcastelli** [comment]
Sure,  will try that out asap.  :)

**Comment by mitar** [comment]
It is without support for using custom class, it is for now just changing that there are classes involved at all.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
