### ISSUE TITLE
Provide templateInstance.children

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#115]
To access all currently available template children for a given template instance.

**Comment by tcastelli** [comment]
This goes in line with what I said about deprecating .parent and I just want to add a few comments.

 - Allowing this to be turned on/off from a config varible could be nice. (Maybe children loops are not always needed and are waisting size for nothing)
-  Instead of keeping the data inside every template, we could store this on a "fast access" parallel structure keeping the template tree structure with the templateInstances(and maybe some staticstics like times viewed, clicked, etc). Keeping this info inside the template is also an option but I think that the cleaner the templates are, the better.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
