### ISSUE TITLE
Feature request: preserve form inputs across hot code reload

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#154]
Migrating this feature request over from meteor/meteor#4058 (Note: since this request was created this feature was implemented in [aldeed:autoform](https://atmospherejs.com/aldeed/autoform) by leveraging `Reload._onMigrate` - see aldeed/meteor-autoform#66). Originally requested by @dandv.

----

Right now, when HCR occurs, form inputs are lost. This can have unwanted consequences especially when a textarea or element with contenteditable=true are re-rendered, and large amounts of user-entered text would be lost.

**Comment by mitar** [comment]
Yes, I think this should be done by a package and does not have to be in core Blaze. But I would be open that this is added to documentation/guide with some best practices.

Personally, I prefer over `Reload._onMigrate` to simply use local storage to store form into it on every change. And then when user clicks submit or cancel, the local storage is cleared. Next time form is rendered, if there is anything in the local storage, that is loaded instead of a default content.

This handles both hot-reload and also browser crashes.

For Blaze Components, I can see this being a mixin.

**Comment by msavin** [comment]
Agree with @mitar - it would be easy to do as a package

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
