### ISSUE TITLE
Blaze re-rendering doesn't keep up with keystrokes

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#157]
Migrating this over from meteor/meteor#4343. I've created an [up to date repro here](https://github.com/hwillson/meteor-issue-4343) (using Meteor 1.4.2.1 and Blaze 2.2.0). This issue is still happening (you just might have to type really really fast to see it, depending on your environment).

![nov-14-2016 14-57-38](https://cloud.githubusercontent.com/assets/137740/20280522/c9758a2e-aa7a-11e6-8531-95d02b315a9c.gif)

----

Original issue (reported by @tmeasday):

Perhaps an addendum to meteor/meteor#3596.

If you bind to a keyup event and resultingly re-render, Blaze doesn't keep up with very rapid typing.

Reproduction: [see updated link above]

1. Place the cursor before the X in one of the fields.
2. Type very rapidly.
3. Note that the cursor moves to the end of the field and text appears after the X.

I can attach a video if it's not clear what I mean.

Note that (for instance), React---where re-rendering is the only way to have text appear in a textfield on user input---does not seem to have this problem.

Tested on a late 2014 iMac so I'm guessing that it'll only be easier to reproduce on less powerful computers.

**Comment by mitar** [comment]
I think this cannot really be solved by Blaze, because it depends on what logic you want. I think [Blaze components](http://components.meteorapp.com/) demo has a solution to this. And this is that when form input gets a focus, you stop helper's reactivity. This also prevents some external change to value (like if you are reading it from Minimongo) to override your changes to a field.
