### ISSUE TITLE
detect if last record in collection

### ISSUE THREAD

**Issue by aadamsx** [meteor/blaze#165]
Using #each, is there a way to detect last record in the collection is reached?

For example: http://stackoverflow.com/questions/26862331/in-meteor-using-each-check-if-last-element-in-the-collection-reached

**Comment by mitar** [comment]
I was always in favor of having things like `@first` `@last` and stuff, but the argument was that `@index` is good enough. Because then you can do things like `{{#if $eq @index collection.count}}` if `$eq` is a helper which checks for comparison (there is one-off issue here though).

So for now one should create a helper.

**Comment by aadamsx** [comment]
Thanks.

So doing something like this might work?

```javascript

Template.myTemplate.helpers({
    likedAnimals: function(){
        var animals = animals.find({}).fetch();
        return animals.map(function(animal, index){
            return {
                name: animal,
                isFirst: index==0,
                isLast: index==animals.length-1
            }
        })
    }
})

```

**Comment by mitar** [comment]
BTW, Minimongo cursors already have `map`. So you do not have to do an array and them map over.

There is also `@index` inside a Blaze template. You can pass that to a helper which computes if this is the last value.

**Comment by aadamsx** [comment]
Thanks.
