### ISSUE TITLE
Spacebars : add support for {{#each object}} where object is an object

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#219]
Migrated over from meteor/meteor#3884.

----

(originally requested by @jeremyfourna)

Hello,

Actually {{#each}} can only iterate through an Array and spacebars doesn't have a {{#for key in object}} method.

It would be great if we don't have to use another templating language to iterate through the properties of an object.
Actually I have to know in advance what are the properties of my objects when I define my templates.

**Comment by mitar** [comment]
I think this is a problematic because order of iteration is not really defined. I would go that we do not support this in Blaze because it encourages a bad programming practice, relaying on the order of keys in an object. And to make that predictable, you have to use custom logic to define it in any way you want. So I am closing for now until somebody makes a strong argument for this.
