### ISSUE TITLE
[Blaze] Spacebars no longer supports block helpers around attributes #1930

### ISSUE THREAD

**Issue by NitroBAY** [meteor/blaze#235]
See https://github.com/meteor/meteor/issues/1930
I would add this : 
`<input checked="">` with HTML5 syntax is considered as a checked box so if I just do `<input checked="">` the input is checked BUT if I create an helper `test` which returns false `<input checked="{{#if test}}true{{/if}}">` the whole checked attribute is removed (so it appears unchecked).
This makes the result of the source code weird and kinda unexpected.
`{{#if true}}checked{{/if}}` is more logical as it corresponds more to the final result.

**Comment by mitar** [comment]
So I do not think we will be adding block helpers support around attributes back (they were never in Blaze, they were in previous rendering engine used by Meteor).

For the issue that with checked attribute, you can open a separate issue. I agree that the behavior you are describing looks not intuitive, but I am not sure if we can change it at this point because of the backwards compatibility. Or is this something which recently broke and it worked before?

**Comment by NitroBAY** [comment]
Everything's working, the behavior is weird/unintuitive that's it. But if you don't want to change it that's fine too.

**Comment by mitar** [comment]
Can you try and see if it is the same weird in v2.1.9 as well?

**Comment by NitroBAY** [comment]
But if you don't want block helpers support around attributes back, then it's normal that `checked="{{test}}"`  with test returning false removes the whole checked attributes otherwise we couldn't reactive set checked. I already use blaze@2.3.0

**Comment by mitar** [comment]
Yes, my question is if this is maybe a regression between 2.1.9 and 2.3.0. Could you check?

**Comment by NitroBAY** [comment]
Okay

**Comment by NitroBAY** [comment]
Same error `A template tag of type BLOCKOPEN is not allowed here.` after downgrading to 2.1.9

**Comment by mitar** [comment]
I was thinking of testing if attribute is removed if in `checked="{{value}}"` `value` is false.

In any case, I do suggest that you open an issue with the problem of `attribute="{{value}}"` not being intuitive when `value` is false.

**Comment by NitroBAY** [comment]
But the attribute is removed if in` checked="{{value}}"` `value` is false.

**Comment by mitar** [comment]
Yea, but I would like to understand if it is removed also on 2.1.9. Is it? Because we were recently changing this code and maybe this is a new issue.

> I don't any option but allowing block helpers support around attributes.

Why? We could maybe make it so that if `value` is an empty strings, attribute is not removed.

I am still trying to understand the problem and history of it. You can help with that.

But yes, `value` is done differently for `checked` attribute than for others. For `checked`, others requested that it should be removed when `value` is false.

**Comment by NitroBAY** [comment]
On feb 2015 one already stated : 

> required is like checked. [...] <input required={{x}}> will omit the attribute if x returns false, undefined or null. You can also write <input {{x}}> where x reactively changes between "required" and "", or a dictionary of attributes and values.

So it seems that it's been the default behavior for a long time, it is not a "new issue".

> We could maybe make it so that if value is an empty strings, attribute is not removed.

It's not a good idea as `checked=""` `checked=false` checked="false` all of these attributes makes the input **checked** only the fact of omitting checked make the input **not checked**. 

> I am still trying to understand the problem and history of it. You can help with that.

I think the actual behavior where checked is omitted if x returns false in `checked={{x}}` is less intuitive that letting people use block helpers around checked `{{#if x}}checked{/if}}` but you said :

>  I do not think we will be adding block helpers support around attributes back

So letting the actual behavior for checked is logical then.
