### ISSUE TITLE
Object property #each list

### ISSUE THREAD

**Issue by janat08** [meteor/blaze#261]
#241 I think that objects could serve better as list rendering way, and I found no issue for it although blaze will promise this feature in console if you try it.

**Comment by mitar** [comment]
Objects do not have a defined or fixed order of properties, so this might not work as you want in `#each`. For example, at every reactive change of the object, the displayed list could be randomly permuted.

Or do you want to iterate in original insert order? This can still be surprising for somebody.

**Comment by janat08** [comment]
well so vue does it, if we're using their tracker may as well steal some of their api.

**Comment by mitar** [comment]
There is also this warning in Vue documentation:

> When iterating over an object, the order is based on the key enumeration order of Object.keys(), which is not guaranteed to be consistent across JavaScript engine implementations.

So, while I think it is OK for libraries to have this feature if they want it, I do not see much addition to existing Blaze usage at this point in the library life, but I also do not see if it would introduce any backwards incompatibilities.

So let's see a bit what others think about this feature and demand for it.

**Comment by janat08** [comment]
You mean you're looking to differentiate blaze from vue as SPA (although really as APIs go vue isn't so much of an SPA) and react as bureaucracy heavy, because playing catch up is losers game.

**Comment by mitar** [comment]
No, I am not saying that we should not implement things for the sake of differentiation. But that this is easily achievable in Blaze with a helper (`{{#each key in toList object}}`) so that I do not see much added value to make core API more complex. And also because it is unclear what semantics would be a good default (in which order to traverse the object) I feel it is not bringing much to the table.

But if people upvote this issue a lot because they really miss this feature, then we could do it.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
