### ISSUE TITLE
DOM does not update when I update helpers

### ISSUE THREAD

**Issue by thislekan** [meteor/blaze#352]
I have an app with a signup form that uses helpers to list out input fields in the form. The input fields are well displayed and all keys in each object in the array are well utilised (so no issues until I try to add something to each object). My template helper looks like in the code below.

```
Template.overrideSignUp.helpers({
fields: [
  {
      _id: 'email',
      label: 'Email',
      displayName: 'Email Address',
      showLabels: true,
      type: 'email'
    },
    {
      _id: 'password',
      label: 'Password',
      displayName: 'Password',
      showLabels: true,
      type: 'password',
      showPassword: true,
    },
]
})
```

The challenge comes from when I try to update the objects due to users actions like submitting the form without filling the input fields. I do something like in the code below:

```
Template.overrideSignUp.events({
'submit .submit-btn': event => {
  // prevent default
  // verify if any of the input field is empty or meets certain conditions
  // if input field is empty add `hasError` & `errorText` to the corresponding input object in the fields array
  // (implementation for the above step is done in the code below) 
  
  const helpers = Template.instance().view.template.__helpers.set('fields', [
      {
      _id: 'email',
      label: 'Email',
      displayName: 'Email Address',
      showLabels: true,
      type: 'email'
    },
    {
      _id: 'password',
      label: 'Password',
      displayName: 'Password',
      showLabels: true,
      type: 'password',
      showPassword: true,
      hasError: true,
      errorText: 'This field is required'
    },
  ])
},
})
```

After updating the fields array and confirming that the fields array was updated using the `Template.instance().view.template.__helpers.get('fields')` method, the UI does not change.

I have been googling for days now to no end and I will appreciate a solution (if any) to my problem.

**Comment by alanning** [comment]
StackOverflow would probably be a better place to post this kind of usage issue as Github Issues is generally used more for things like bug reports.

In your case I think overriding the helpers with an array instead of a function as it generally expects is breaking the "reactive" nature of helpers.  You can see an example of how helpers are defined using functions here:
http://blazejs.org/guide/spacebars.html

In you case, try something like this:

```
Template.overrideSignUp.helpers({
  fields: function () {
    return [
      {
          _id: 'email',
          label: 'Email',
          displayName: 'Email Address',
          showLabels: true,
          type: 'email'
        },
        {
          _id: 'password',
          label: 'Password',
          displayName: 'Password',
          showLabels: true,
          type: 'password',
          showPassword: true,
        },
    ]
  }
})
```

Next step is to have the values of the array be calculated based on the value of some ReactiveVar that is set in an event handler.  So user performs some action, the ReactiveVar gets changed, the "fields" helper is re-executed (because its reactive), and the form updates based on the new "fields" values.

You can see an example of defining the ReactiveVar in the onCreated callback here:
http://blazejs.org/api/templates.html#Template-onCreated

You might also consider using SimpleSchema to do validation, here's an example from the Todos example app:
https://github.com/meteor/todos/blob/master/imports/ui/components/lists-show.js#L33
