### ISSUE TITLE
[Idea] Describe test execution

### ISSUE THREAD

**Issue by b-long** [meteor/blaze#70]
In support of #59 , can we also describe how a typical developer can execute the tests?  I'm new to both Circle CI and Meteor and I'm having some trouble understanding the commands to execute.  In the Meteor ecosystem, I've only managed to [bootstrap my own tests](https://github.com/b-long/meteor-ci-example/blob/master/README.md) using [spacejam](https://github.com/practicalmeteor/spacejam) for CI environments.

In any case, I've tried to deconstruct your [circle.yml](https://github.com/meteor/blaze/blob/94a455179ebb586a7616d57c681b976a9a854efe/circle.yml) file and the best I can figure out is that I may need to do something like this : 

``` shell
git clone git@github.com:meteor/blaze.git
cd blaze 
git submodule sync
git submodule update --init --recursive
<something> tests/test-runner/test-all.sh
```

**Comment by mitar** [comment]
I think easier is to clone with `--recursive`:

```
git clone --recursive https://github.com/meteor/blaze.git
```

And then follow instructions [here](https://github.com/tozd/meteor-test-runner#using-the-complete-test-suite).

**Comment by lucfranken** [comment]
Did a git clone --recursive and followed the instructions above on OSx 10 and it works, the tests start running. That being said, they are slow, as in really slow to me. When looking into it I noticed they are just TinyTest tests. 

Not sure if this is in the guide since it's offline today:

To run them I did this:

I created a meteor app, so my directory structure is:

- blaze (made by: `git clone --recursive https://github.com/meteor/blaze.git`)
- blazeApp (made by: `meteor create blazeApp`)

Then I did on the command line:

```sh
cd blazeApp
ln -s ../blaze/packages/ packages
```

That creates a symlink to the blaze source packages folder. So now blazeApp thinks it has a local package blaze.

And then run:

```sh
meteor test-packages --port 3505
```
(port is flexible off course)

Now you can open the TinyTest interface in your browser and it will run all blaze tests:

<img width="673" alt="schermafbeelding 2016-09-09 om 10 16 46" src="https://cloud.githubusercontent.com/assets/1609379/18380255/c637069a-7676-11e6-8915-34bc1ba85f7c.png">

When you change things in blaze it will just reload as usual.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
