### ISSUE TITLE
Handlebars vs. #each .. in syntax

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#89]
It seems [Handlebars has a different](handlebarsjs.com/block_helpers.html#block-params) `#each .. in` syntax:

Instead of:

``` handlebars
{{#each user in users}}
  Name: {{user.name}}
{{/each}}
```

``` handlebars
{{#each users as |user index|}}
  Index: {{index}} Name: {{user.name}}
{{/each}}
```

And interesting feature is that you can access also the index of the iteration. Does `#each .. in` syntax supports that? Should we expose index somehow? Should we support this alternative syntax as well?

**Comment by stubailo** [comment]
I thought blaze supports @index?

**Comment by mitar** [comment]
How does this work with nested `#each .. in`? You cannot rename outside `@index`, no?

**Comment by mitar** [comment]
I would propose that we might introduce:

```handlebars
{{#each user, index in users}}
  Name: {{user.name}}
{{/each}}
```

**Comment by stubailo** [comment]
Can't you do "let myIndex=@index"? (Sorry on mobile)

**Comment by mitar** [comment]
Good question. :-) I will have to check. (Agh, we do not have online Blaze compiler website.)

**Comment by stubailo** [comment]
I still strongly believe that handlebars syntax is not good and we should basically ignore it, but of course it's ultimately up to you.

**Comment by mitar** [comment]
I agree that this is really bad. This is why I would propose this syntax:

```
{{#each user, index in users}}
  Name: {{user.name}}
{{/each}}
```

But I would also like to keep this ticket around so that people who are maybe coming from Handlebars can vote if they really want this original syntax ({{#each users as |user index|}}). But I am not eager to implement it. :-)

**Comment by aadamsx** [comment]
I agree.  We should strive to not be too idealistic.  We were born from handlebars but do not have to live in its shadow forever. 

We should try to agree on a few core principles and shape our priorities around them.

**Comment by stubailo** [comment]
I think having a nice syntax is one of the main things that made blaze better than angular. So in my mind it's one of the core goals of the library to have a nice and readable template language.

**Comment by mitar** [comment]
Hm, this looks pretty ugly:

```handlebars
  {{#each user in users}}
    {{#let userIndex=@index}}
      {{#each name in user.names}}
        <p>{{@index}} {{userIndex}}</p>
      {{/each}}
    {{/let}}
  {{/each}}
```

I think this would be better:

```handlebars
  {{#each user, userIndex in users}}
    {{#each name, nameIndex in user.names}}
      <p>{{nameIndex}} {{userIndex}}</p>
    {{/each}}
  {{/each}}
```

**Comment by aadamsx** [comment]
I agree with @stubailo here too, this should be a goal, Blaze should have a buttery smooth, easy to grasp and reason about syntax.  

I don't know, maybe add it as priority number 2 or 3.  

But if we adopt a goal of making moving Blaze to a more componentization architecture in the future, this could  affect things like syntax for better or worse as well.

**Comment by stubailo** [comment]
Yeah I like it! Especially since it matches JavaScript forEach

**Comment by aadamsx** [comment]
I agree with @stubailo here too, this should be a goal, Blaze should have a buttery smooth, easy to grasp and reason about syntax.

I don't know, maybe add it as priority number 2 or 3.

But if we adopt a goal of making moving Blaze to a more componentization architecture in the future, this could affect things like syntax for better or worse as well.

**Comment by aadamsx** [comment]
The second is intuitive -- I like it.

**Comment by lucfranken** [comment]
Second one looks great. Totally agree with @stubailo that it matches forEach which is great.

We should be a bit careful and think about whether we promote this strongly. See for example: https://forums.meteor.com/t/if-blaze-improved-significantly-would-you-go-back-to-it/29016/68

Building loops in loops sometimes is necessary but I don't think we should promote it too strong. An alternative for the example would be a template users and a template userNames. Which removes all scoping issues.

**Comment by aadamsx** [comment]
To me, a setup like, where we have a ```<li>``` as a component is small for the sake of being small -- not that useful because I probably won't be able to use it in many places.  

I want something **can make small**, **dynamic**, and **use in a lot of places** to identify candidates for componentization -- not all UI elements match these criteria.  

In my experience, lists you iterate over don't really match these three criteria, and are almost always unique to the page.  

Lists, Tables, generally speaking #each loops like what we've been discussing here match only two:

* can make small (like your example)
* are used in a lot of places
x but are really hard to make dynamic

In the times where you do have a list used in more than one place, it's probably a good idea to break it out, but not down to the ```<li>``` level, because it's hard to make it dynamic.

When we do break something like a list down to the ```<ul>``` level, I'd like to know I have a pattern like the following in my toolkit:

```
  // list-component.js
  <ul>
  {{#each user, userIndex in users}}
    {{#each name, nameIndex in user.names}}
      <li>{{nameIndex}} {{userIndex}}</li>
    {{/each}}
  {{/each}}
  </ul>
```

**Comment by lucfranken** [comment]
I see how you get there, yes you make things completely flexible. Agree that sometimes that's useful. As stated before I certainly think the each concept is worth a lot and is a great addition.

We both have a very different approach which I like. Where we don't put any logic in the templates when we can (mostly only simple if statements) and we don't use with tags or whatever you use the whole package.

As you also wrote, we don't see a lot of re-use in those kind of lists. We make them in a non-reusable way in general. Problem we run into regularly when we would make things very flexible like in your example is that we get lots of if statements in ulList1 and liList1 to handle the differences between instances of it. 

So we do it the other way around: we make them small and specific and create very small components we re-use. In my example below the image.

Just wanted to show you how we would approach your example: I made a clear example of bikes because that's how we do it. We don't make general list templates or something. We name them specifically to the business value.

```handlebars
<!--landing-dashboard.html -->
<template name="dashboard">
  {{> listOfBikes}}
</template>

<!--listOfBikes.html -->
<template name="listOfBikes">
  <ul>
    {{#each bikes}}
      {{> bike}}
    {{/each}}
  </ul>
</template>

<template name="bike">
  <li>
      {{frameNumber}}: {{color}}
      {{> image url = url}}
  </li>
</template>
```

```javascript
Template.listOfBikes.helpers({
  bikes() {
    return Bikes.find();
  }
});
Template.bike.helpers({
  url() {
    return someUrlParser(this._id);
  }
});
```

Again: Not saying one solution is better. I think it's important that Blaze gives a quite clear indication on how to solve those common issues. Maybe even multiple approaches so people can see the options. I have the feeling many now start with big templates which causes mess.

So people start understanding the way they can use Blaze. That will strengthen the community and communication while still keeping all options open. You make a list your way, I make it mine, and we are both happy with our solution and Blaze.

**Comment by mitar** [comment]
@lucfranken: Remember also, that while currently Blaze templates are like snippets and you can combine them as you want and they inherit the outside scope, we are planing to move into a direction where they do not inherit anything automatically but you have to provide things explicitly. In this case then it means that you have to pass through context of two levels up, if you need that.

Also, your examples are in fact single loop, show me an example with double loop and explicit passing of outside index in. :-)

**Comment by necmettin** [comment]
```
  {{#each user, userIndex in users}}
    {{#each name, nameIndex in user.names}}
      <p>{{nameIndex}} {{userIndex}}</p>
    {{/each}}
  {{/each}}
```
I have a suggestion about this. In all the programming and templating languages that support similar access (that I know of; for example Python, Jinja, Twig, Django, PHP foreach, Swift), it is `key/index, value`, not `value, key/index`. I believe `index, element` would be much more intuitive and easier to adopt.

**Comment by mitar** [comment]
JavaScript's [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) has `element, index`, but jQuery [each](https://api.jquery.com/each/) does have `index, element`.

OK, which one people prefer? Upvote this comment if you want `element, index`, and the comment above by @necmettin, if you prefer `index, element`.

**Comment by mitar** [comment]
> Can I find an example of that? Is that this issue?

It is mostly ideas in #75, I do not think we have a more concrete place where we are discussing it now, but I got reading of the community that this direction is pretty supported ([7 upvotes, no downvotes](https://github.com/meteor/blaze/issues/75#issuecomment-244273013)).

> Off course simplified way, we make those objects reactive for example.

I am not sure if we are talking about the same thing, but I would like to see Blaze/template example of two levels of loops, with indexes, and subtemplates, with explicit passing of arguments. How would that be in comparison with mine:

```handlebars
  {{#each user, userIndex in users}}
    {{#each name, nameIndex in user.names}}
      <p>{{nameIndex}} {{userIndex}}</p>
    {{/each}}
  {{/each}}
```

> If the index is of business value (like the preferenceIndex) then it's part of the data. So that's available by that.

Yes, sometimes you just want to use index for CSS classes.

But I think we are agreeing that this feature would help in some cases, and in some other would make it maybe too complicated. And that there is a good practice that you put things into subtemplates. But I am not sure why would that be the only option we should allow, if you have some cases where it just makes sense to not do it. It is like array comprehensions in Python. You do not need them, they can be misused, but sometimes they are simply much more readable than anything else.

**Comment by lucfranken** [comment]
> It is mostly ideas in #75, I do not think we have a more concrete place where we are discussing it now

ok, clear, maybe we should do that discussion in a separate issue. I think it's one of the main important issues for Blaze: The experience and simplicity you can start with. If it's then also a very powerful tool I think that's where Blaze already shines and will improve even more with all those enhancements.

> But I think we are agreeing that this feature would help in some cases, and in some other would make it maybe too complicated.

Totally agree, that's why I started my post with:

https://github.com/meteor/blaze/issues/89#issuecomment-245838793
> Second one looks great. Totally agree with @stubailo that it matches forEach which is great.
> We should be a bit careful and think about whether we promote this strongly.

For me it's about the Blaze experience in general, not specially on this each structure. I hope we can make the examples reflect the simplicity and good overview of your code (when done well) with Blaze. So the user has the feeling it instantly understands it.

On that:

```handlebars
  {{#each user, userIndex in users}}
    {{#each name, nameIndex in user.names}}
      <p>{{nameIndex}} {{userIndex}}</p>
    {{/each}}
  {{/each}}
```

Love the fact that you inherit the scope so that userIndex becomes available all below. We should be aware of what happens when you get:

```handlebars
  {{#each user, userIndex in users}}
    {{#each name, nameIndex in user.names}}
      <p>{{nameIndex}} {{userIndex}}</p>
      {{#each friendName, userIndex}}
        {{friendName}} is my nr {{userIndex}} friend
      {{/each}}
    {{/each}}
  {{/each}}
```

It should raise a very clear exception maybe? Lots of little Javascript bugs happen with overwriting the var i; in loops for example when copying an example piece of code.

Same with:

```handlebars
  {{#each user, userIndex in users}}
    {{#each name, nameIndex in user.names}}
      <p>{{nameIndex}} {{userIndex}}</p>
      {{#each friendName, userIndex in user.friends}}
        {{> friend}}
      {{/each}}
    {{/each}}
  {{/each}}
```

When re-using the variable name it should raise an error I think. So you don't get implicit overwrites which can cause headaches. Basically I think they should be seen as a const, you cannot overwrite them. That increases maintainability of the codebase.

Also what I was thinking about: It's not really about the index but about the key right? ForEach in javascript is working on basically any iterator (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Iteration_protocols). So if you want a numeric index you send in something like an array. But if you send something else it behaves the same as javascript? So:

```javascript
Template.users.helpers({
  users() {
    let users = new Map();
    users.add('id1', { name: 'John' });
    users.add('id2', { name: 'Jane' });
    return users;
  },
});
```

```handlebars
  {{#each user, userId in users}}
    {{userId}}: {{user.name}}
  {{/each}}
```

Expected output:

```
  id1: John
  id2: Jane
```

Is that consistent with your idea?

**Comment by mitar** [comment]
> Could you re-define {{userIndex}} in friend template?

No, because you would have to explicitly pass it in to be available there.

> When re-using the variable name it should raise an error I think. 

I do not think so. For that one should use linting tools. We could provide some warnings during development maybe.

> Is that consistent with your idea? 

But how you control the order of iteration over the map? When displaying, you probably want to control that.

**Comment by lucfranken** [comment]
> > Could you re-define {{userIndex}} in friend template?

> No, because you would have to explicitly pass it in to be available there.

Ok, yes, that's your point on no scope anymore. I am really worried on that one since it makes stuff much more complex in my opinion. But that's because I only have those simple templates maybe. Really interested in how that would look from your point of view. 

Maybe this one should have a different issue? It's likely the most biggest breaking change in Blaze if you have to manually assign all variables in your template.

> > When re-using the variable name it should raise an error I think.

> I do not think so. For that one should use linting tools. We could provide some warnings during development maybe.

Would for sure do that during development. How that would be implemented I don't know, I am not enough into build tools to give a good opinion on that. 

> > Is that consistent with your idea?

> But how you control the order of iteration over the map? When displaying, you probably want to control that.

That's data logic, not template logic. So it belongs in the helper in the most basic implementations:

```handlebars
Template.users.helpers({
  users() {
    return Meteor.users.find({}).sort({ likes: -1 });
  },
});
```

In bigger applications you should move that more likely to an object:

```handlebars
Template.users.helpers({
  users() {
    return UsersObject.getLikesTop(10);
  },
});
```

I think, based on your answers I now get your point of view more. Do you want to add all those kinds of features to Blaze? Like sorting, filtering etc?

**Comment by mitar** [comment]
> I am really worried on that one since it makes stuff much more complex in my opinion.

I think even beginner programmers are used to pass arguments when they are calling another function.

> Maybe this one should have a different issue? It's likely the most biggest breaking change in Blaze if you have to manually assign all variables in your template.

Yes, this is why we are not yet planing to do it. :-)

And yes, we should probably create a ticket to track discussion about it.

> That's data logic, not template logic. So it belongs in the helper in the most basic implementations:

Yes, but objects and many iterators do not have a defined order of iterating. So this is why I am saying that it is questionable how useful this is for things besides cursors and arrays.

> Do you want to add all those kinds of features to Blaze? Like sorting, filtering etc?

No.

**Comment by guidouil** [comment]
Regarding the sorting part. I had to do it in last place for some reason. I did a template helper that get the array and sort it with the second param and you can pass that as additional arguments of a #each to have the content sorted. My 2c ^_^
```js
Template.main.helpers({
  sortBy (array, field) {
    return _.sortBy(array, field);
  },
});
```

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
