### ISSUE TITLE
Change file extension to .blaze

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#97]
To make it easier for editors and syntax highlighters to know that a file is a Blaze template, I think we might want to consider changing the file extension to `.blaze`.

I think this can be done in a backwards compatible way as follows: `blaze` (and `templating`) package by default processes only `.blaze` extension, but if you use `blaze-html-templates` package, then also `.html` extension is processed.

**Comment by stubailo** [comment]
Why not `.blaze.html`? I find that HTML syntax highlighting is more than sufficient for my needs.

**Comment by mitar** [comment]
But there are also handlebars syntax highlighting inside. Also WebStorm generally knows how to resolve them such symbols inside handlebars.

**Comment by stubailo** [comment]
Yeah I guess in my mind making the extension not `html` will _significantly_ damage the "normal" experience when there is no special tooling. Which is the experience I use normally.

**Comment by mitar** [comment]
Aren't you using React these days? How does `jsx` extension help you?

**Comment by aadamsx** [comment]
> But there are also handlebars syntax highlighting inside.

And by using a .blaze extension, can't we have more control over syntax highlighting?  Also, will this allow us to replace ```<blaze>``` with ```<script>``` to denote events/helpers within a ```<template>``` tag?

**Comment by stubailo** [comment]
> How does jsx extension help you?

I don't use `.jsx`, I simply use `.js`.

**Comment by mitar** [comment]
How does then your editor fail on HTML tags? :-)

**Comment by mitar** [comment]
> Also, will this allow us to replace `<blaze>` with `<script>` to denote events/helpers within a `<template>` tag?

Did we ever talked about `<blaze>` tag?

**Comment by necmettin** [comment]
How about keeping .html only for <template> files, and using .blaze when <template>, helpers and methods combined? This would be both backwards compatible and could make writing Blaze code easier (as you know, the second part is discussed in #94).

**Comment by mitar** [comment]
I do not think this helps at all with the fact that people might want to use `.html` for static HTML (or valid HTML, like one with web components).

**Comment by lucfranken** [comment]
Example currently in Sublime 2 of a bit with too much logic:

<img width="387" alt="schermafbeelding 2016-09-14 om 10 30 50" src="https://cloud.githubusercontent.com/assets/1609379/18505170/5770c306-7a66-11e6-8add-db496ad36a7b.png">

If it would improve syntax highlighting that would be a great addition. I am sure there are also lots of plugins to do that, which I never seem to find working great, but it would be a great addition. 

Not sure whether that fully depends on the extension. It seems most Blaze is also valid HTML just not parsed. When it's stays valid HTML there would not be a big issue I think. When adding more features which are not supported by HTML  it would make sense to choose another extension because well, it's invalid.

**Comment by alexandesigner** [comment]
I like the idea to use the extension ``.blaze`` with this change, we would bring the idea of [Single File Components](https://vuejs.org/guide/application.html#Single-File-Components) an interesting approach..  

Maybe it would be easier to encapsulate the css and javascript, as well as specify the language ``sass`` | ``less`` | ``stylus`` | ``coffe`` | ``jade`` https://github.com/meteor/blaze/issues/94

**Comment by mitar** [comment]
Just for the record, changing the extension has nothing with features. We already discussed ideas in #94. So we will be using `<script>` tag inside the files to have code there. And one could also use `<style>` tags in a similar way or something like that.

So this just a question to not confuse Blaze files with other files which might be static HTML.

**Comment by tcastelli** [comment]
I think the support/change to .blaze extension would be great/is needed with next blaze version which could include single componentes, new syntax or whatever, but for now, and to keep backwards compatibility, I would leave it as .html

**Comment by mitar** [comment]
Because syntax of new single-components files will be backwards compatible with old syntax, we could be reusing `.html` extension. And both `.html` and `.blaze` can support both.

My personal argument for this change is that I would also like to move Blaze to support server-side templates. And so my proposal is that we support on the client `.blaze` and `.html` which effectively work the same, with a way to disable `.html`, and on the server-side only `.blaze` (or maybe the same way to enable/disable `.html`).

**Comment by tcastelli** [comment]
I get the point, and for ssr it would be really useful to have a blaze extension,  but since none of this was thought at the beginning of blaze, it may be hard to explain to newcomers that they can use html (or not with some sort of option) but only on the client and blaze extension on both. (or at least the explanation sounds weird to me)

imo,  I think the new .blaze extension should come after a previous deprecation of html files (they could be used with new features as you said for the time they are supported) and then on a next version drop html and go for   .blaze processing only, which makes more sense for the language, especially if changing of introducing new syntax to the handlebars base.

**Comment by msavin** [comment]
Maybe .bml would be better? Blaze Markup Language.

**Comment by tcastelli** [comment]
Both sound fine to me, however .bml files already exist (for image libraries), and as far as I know, .blaze is not being used.

**Comment by goocastro** [comment]
I upvote this.
Blaze files are not valid HTML.
It messes up with every editor's syntax highlighter and, in many cases, with indentation.

If for some people is still an issue to change the file extension, it would be nice at least to accept files with the chosen extension like `.blaze`, `.spacebars` or any other, keeping `.html` when wanted.

**Comment by goocastro** [comment]
Just adding some other extension to this array would be enough?

https://github.com/meteor/blaze/blob/master/packages/templating-compiler/compile-templates.js

````
Plugin.registerCompiler({
  extensions: ['html', 'blaze'],
  archMatching: 'web',
  isTemplate: true
}, () => new CachingHtmlCompiler(
  "templating",
  TemplatingTools.scanHtmlForTags,
  TemplatingTools.compileTagsWithSpacebars
));
````

**Comment by mitar** [comment]
Yes.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
